# Request an environment that provides sudo (that goes with larger containers)
# and a minimal language environment.
sudo: true
language: minimal

cache: cargo

branches:
  only:
  - master

env:
  global:
    - RUST_BACKTRACE=1
  matrix:
    # set RUST_TOOLCHAIN either 'stable' or 'nightly'
    - RUST_TOOLCHAIN=stable TARGET=wasm-build
    - RUST_TOOLCHAIN=stable TARGET=runtime-test
    - RUST_TOOLCHAIN=stable TARGET=build-client

before_install:
  # Check how much space we've got on this machine.
  - df -h

script:
  - ./ci/script.sh

after_script:
  # Check how much free disk space left after the build
  - df -h