[package]
name = "centrifuge-chain"
version = "2.0.0"
authors = ["Centrifuge <admin@centrifuge.io>"]
description = "Centrifuge chain implementation in Rust."
build = "build.rs"
edition = "2018"
license = "LGPL-3.0"
default-run = "centrifuge-chain"
homepage = "https://centrifuge.io/"
repository = "https://github.com/centrifuge/centrifuge-chain"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[badges]
travis-ci = { repository = "centrifuge/centrifuge-chain", branch = "master" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "centrifuge/centrifuge-chain" }
is-it-maintained-open-issues = { repository = "centrifuge/centrifuge-chain" }

[[bin]]
name = "centrifuge-chain"
path = "src/main.rs"

[workspace]
members = [
    "pallets/bridge-mapping",
    "runtime",
]

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
serde = { version = "1.0.106", features = ["derive"] }
futures = { version = "0.3.1", features = ["compat"] }
hex-literal = "0.2.1"
jsonrpc-core = "15.1.0"
jsonrpc-core-client = { version = "15.1.0", features = ["http", "ws"] }
jsonrpc-derive = "15.1.0"
jsonrpc-pubsub = "15.1.0"
log = "0.4.8"
structopt = { version = "0.3.8" , optional = true }
serde_json = "1.0"

# primitives
sp-authority-discovery = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sp-consensus-babe = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
grandpa-primitives = { package = "sp-finality-grandpa", git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sp-core = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sp-runtime = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sp-timestamp = { default-features = false,  git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
#sp-finality-tracker = { branch = "rococo-v1", default-features = false,  git = "https://github.com/paritytech/substrate.git" }
sp-inherents = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sp-consensus = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sp-transaction-pool = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sp-api = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sp-blockchain = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sp-block-builder = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sp-runtime-interface = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "centrifuge" }
sp-io = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "centrifuge" }
sp-trie = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "centrifuge" }
sp-keystore = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "centrifuge" }

# client dependencies
sc-client-api = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-chain-spec = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-consensus = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-transaction-pool = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-telemetry = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-network = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-consensus-babe = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
grandpa = { package = "sc-finality-grandpa", git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-finality-grandpa-rpc = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-client-db = { default-features = false, git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-offchain = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-rpc = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-basic-authorship = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-service = { default-features = false, git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-cli = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-executor = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-consensus-epochs = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-consensus-babe-rpc = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-authority-discovery = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-rpc-api = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-keystore = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-tracing = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sc-sync-state-rpc = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
substrate-prometheus-endpoint = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sp-session = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sp-offchain = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
sp-consensus-aura = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }

# Cli specific
frame-benchmarking-cli = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
node-inspect = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }

# frame dependencies
pallet-transaction-payment-rpc = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
substrate-frame-rpc-system  = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
pallet-im-online = { default-features = false, git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }

# Cumulus dependencies
cumulus-client-network = {git = 'https://github.com/centrifuge/cumulus', branch = "centrifuge"}
cumulus-client-consensus-relay-chain = {git = 'https://github.com/centrifuge/cumulus', branch = "centrifuge"}
cumulus-primitives-core = {git = 'https://github.com/centrifuge/cumulus', branch = "centrifuge"}
cumulus-client-service = {git = 'https://github.com/centrifuge/cumulus', branch = "centrifuge"}
cumulus-client-consensus-aura = {git = 'https://github.com/centrifuge/cumulus', branch = "centrifuge"}
cumulus-client-consensus-common = {git = 'https://github.com/centrifuge/cumulus', branch = "centrifuge"}
cumulus-primitives-parachain-inherent = {git = 'https://github.com/centrifuge/cumulus', branch = "centrifuge"}
cumulus-client-cli = {git = 'https://github.com/centrifuge/cumulus', branch = "centrifuge"}

# Polkadot dependencies
polkadot-parachain = {git = "https://github.com/centrifuge/polkadot", branch = "centrifuge" }
polkadot-primitives = {git = "https://github.com/centrifuge/polkadot", branch = "centrifuge" }
polkadot-service = {git = "https://github.com/centrifuge/polkadot", branch = "centrifuge" }
polkadot-cli = {git = "https://github.com/centrifuge/polkadot", branch = "centrifuge" }

# node-specific dependencies
node-runtime = { package = "centrifuge-chain-runtime", path = "runtime" }
node-primitives = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }

[build-dependencies]
vergen = "3.0.4"
substrate-build-script-utils  = { optional = true, git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }

[dev-dependencies]
#sc-keystore = { branch = "rococo-v1", git = "https://github.com/paritytech/substrate.git" }
sc-service-test = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
tempfile = "3.1.0"
sp-keyring = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
frame-system = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }
pallet-transaction-payment = { git = "https://github.com/centrifuge/substrate", branch = "centrifuge" }

[features]
default = [ "std" ]
std = [
	"sc-service/db",
	"structopt",
	"substrate-build-script-utils",
	"sp-consensus-babe/std"
]
