version: '3'
services:
  node_alice:
    container_name: alice
    image: "parity/polkadot:v0.9.12"
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    volumes:
      - type: bind
        source: ./res/rococo-local.json
        target: /chainspec.json
        read_only: true
    command: >
      --chain=/chainspec.json
      --wasm-execution=compiled
      --execution=wasm
      --no-beefy
      --base-path=/data
      --port 30333
      --rpc-port 9933
      --ws-port 9944
      --rpc-external
      --rpc-cors all
      --ws-external
      --rpc-methods=Unsafe
      --alice
      --log="main,debug"

  node_bob:
    container_name: bob
    image: "parity/polkadot:v0.9.12"
    ports:
      - "30344:30333"
      - "9935:9933"
      - "9945:9944"
    volumes:
      - type: bind
        source: ./res/rococo-local.json
        target: /chainspec.json
        read_only: true
    command: >
      --chain=/chainspec.json
      --base-path=/data
      --wasm-execution=compiled
      --execution=wasm
      --no-beefy
      --port 30333
      --rpc-port 9933
      --ws-port 9944
      --rpc-external
      --ws-external
      --rpc-cors all
      --rpc-methods=Unsafe
      --bob
      --log="main,info"

  para_alice:
    container_name: para_alice
    #image: "centrifugeio/centrifuge-chain:parachain-20211012001639-424de85"
    #image: "centrifugeio/centrifuge-chain:parachain-polkadot-v0.9.11-latest"
    image: "centrifugeio/centrifuge-chain:parachain-20211028172939-1696118"
    ports:
      - "30433:30333"
      - "9943:9933"
      - "9954:9944"
    volumes:
      - type: bind
        source: ./res/rococo-local.json
        target: /chainspec.json
        read_only: true
      - type: bind
        source: ./res/altair-dev.json
        target: /altair.json
        read_only: true
    command: >
      centrifuge-chain
      --chain=/altair.json
      --alice
      --parachain-id=2000
      --base-path=/data
      --wasm-execution=compiled
      --execution=wasm
      --rpc-external
      --rpc-cors all
      --ws-external
      --rpc-methods=Unsafe
      --log=main,debug
      --
      --wasm-execution=compiled
      --execution=wasm
      --chain=/chainspec.json

  para_bob:
    container_name: para_bob
    image: "centrifugeio/centrifuge-chain:parachain-20211028172939-1696118"
    ports:
      - "30434:30333"
      - "9946:9933"
      - "9955:9944"
    volumes:
      - type: bind
        source: ./res/rococo-local.json
        target: /chainspec.json
        read_only: true
      - type: bind
        source: ./res/altair-dev.json
        target: /altair.json
        read_only: true
    command: >
      centrifuge-chain
      --chain=/altair.json
      --bob
      --parachain-id=2000
      --base-path=/data
      --wasm-execution=compiled
      --execution=wasm
      --rpc-external
      --rpc-cors all
      --ws-external
      --rpc-methods=Unsafe
      --log=main,info
      --
      --wasm-execution=compiled
      --execution=wasm
      --chain=/chainspec.json
