[package]
name = 'pallet-crowdloan-reward'
description = 'Module for processing crowdloan claim rewards.'
authors = ['The Centrifugians Tribe']
edition = '2018'
homepage = 'https://centrifuge.io'
license = "LGPL-3.0"
repository = 'https://github.com/centrifuge/centrifuge-chain'
version = '0.0.1'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
frame-support = { branch = "rococo-v1", git = "https://github.com/paritytech/substrate.git", default-features = false }
frame-system = { branch = "rococo-v1", git = "https://github.com/paritytech/substrate.git", default-features = false }
frame-benchmarking = { branch = "rococo-v1", git = "https://github.com/paritytech/substrate.git", default-features = false, optional = true }
log = { version = "0.4.14", default-features = false }
sp-runtime = { branch = "rococo-v1", git = "https://github.com/paritytech/substrate.git", default-features = false }

[dev-dependencies]
serde = { version = "1.0.119" }
sp-core = { branch = "rococo-v1", git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-io = { branch = "rococo-v1", git = "https://github.com/paritytech/substrate.git", default-features = false }

[features]
default = ['std']
std = [
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'log/std',
]

runtime-benchmarks = ["frame-benchmarking"]