[package]
name = "runtime-integration-tests"
version = "0.1.0"
authors = ["Centrifuge <admin@centrifuge.io>"]
edition = "2021"
license = "LGPL-3.0"
homepage = "https://centrifuge.io/"
repository = "https://github.com/centrifuge/centrifuge-chain"


[dependencies]

# Substrate
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }

# Polkadot
kusama-runtime = {git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
pallet-xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
polkadot-parachain = {git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
polkadot-primitives = {git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
xcm-builder = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
xcm-simulator = { git = "https://github.com/paritytech/polkadot", default-features = false , branch = "release-v0.9.16" }

# Cumulus
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.16" }
parachain-info = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.16" }

# Orml pallets
orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, branch = "polkadot-v0.9.16" }
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, branch = "polkadot-v0.9.16" }
orml-xcm-support = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, branch = "polkadot-v0.9.16" }
orml-xtokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, branch = "polkadot-v0.9.16" }

# Misc
xcm-emulator = { git = "https://github.com/shaunxw/xcm-simulator", branch="master" }

# Local
runtime-common = { path = "../common" }
development-runtime = { path = "../development" }
common-traits = { path = "../../libs/common-traits" }
