[package]
name = "runtime-integration-tests"
version = "0.1.0"
authors = ["Centrifuge <admin@centrifuge.io>"]
edition = "2021"
license = "LGPL-3.0"
homepage = "https://centrifuge.io/"
repository = "https://github.com/centrifuge/centrifuge-chain"


[dependencies]
xcm-simulator = { git = "https://github.com/paritytech/polkadot", default-features = false , branch = "release-v0.9.16" }

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-aura = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16"}
pallet-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16"}
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-bounties = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-collective = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-democracy = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16", default-features =false }
pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-indices = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-membership = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-multisig = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-offences = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-proxy = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-recovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16", features = ["historical"] }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-sudo = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-staking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }

# Polkadot dependencies
polkadot-parachain = {git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
polkadot-primitives = {git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
xcm-executor = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
xcm-builder = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
pallet-xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
kusama-runtime = {git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }


# cumulus
cumulus-pallet-aura-ext = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.16" }
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.16" }
cumulus-primitives-utility = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.16" }
cumulus-primitives-timestamp = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.16" }
cumulus-pallet-parachain-system = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.16" }
cumulus-pallet-dmp-queue = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.16" }
cumulus-pallet-xcmp-queue = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.16" }
cumulus-pallet-xcm = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.16" }
parachain-info = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.16" }

# orml pallets
orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, branch = "polkadot-v0.9.16" }
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, branch = "polkadot-v0.9.16" }
orml-xcm-support = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, branch = "polkadot-v0.9.16" }
orml-xtokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, branch = "polkadot-v0.9.16" }

runtime-common = { path = "../common" }
development-runtime = { path = "../development" }
common-traits = { path = "../../libs/common-traits" }

[dev-dependencies]
env_logger = "0.9.0"
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }

cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.16" }
cumulus-test-relay-sproof-builder = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.16" }

polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
kusama-runtime = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }

xcm-emulator = { git = "https://github.com/shaunxw/xcm-simulator", branch="master" }
