[package]
authors = ["Centrifuge <admin@centrifuge.io>"]
description = 'Loan pallet for runtime'
edition = '2018'
license = "LGPL-3.0"
name = 'pallet-loan'
repository = "https://github.com/centrifuge/centrifuge-chain/pallets/nav-feed"
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
serde = { version = "1.0.102" }
codec = { package = 'parity-scale-codec', version = '2.0.0', features = ['derive'] , default-features = false }
# fixed = { package = "substrate-fixed", git = "https://github.com/encointer/substrate-fixed", default-features = false , features = ["serde"], branch = "master" }

frame-support = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
frame-system = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
sp-runtime = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
sp-std = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-arithmetic = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-timestamp = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }

# our pallets
pallet-pool = { path = "../pool", default-features = false}

[dev-dependencies]
sp-core = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
sp-io = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
pallet-randomness-collective-flip = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-balances = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-authorship = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-timestamp/std',
    'pallet-pool/std'
]
